[versions]
agp = "8.13.2"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.3"
composeBom = "2026.01.01"

kspVersion = "2.2.21-2.0.4"
daggerHiltVersion = "2.58"
hiltComposeVersion = "1.3.0"

androidRoomVersion = "2.8.4"

navComponentVersion = "2.9.7"

coroutinesVersion = "1.10.2"

datastoreVersion = "1.2.0"

androidxIconVersion = "1.7.8"
material3 = "1.4.0"
uiVersion = "1.10.2"

coroutinesTestVersion = "1.10.2"
googleTruthVersion = "1.4.5"
mockkVersion = "1.14.9"
turbineVersion = "1.2.1"
androidArchTestingVersion = "2.2.0"
coreKtxVersion = "1.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHiltVersion" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "daggerHiltVersion" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "daggerHiltVersion" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltComposeVersion" }


room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidRoomVersion" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidRoomVersion" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidRoomVersion" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "androidRoomVersion" }

navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navComponentVersion" }
navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navComponentVersion" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesVersion" }

datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreVersion" }

androidx-icon = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "androidxIconVersion" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "uiVersion" }


kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTestVersion" }
google-truth = { group = "com.google.truth", name = "truth", version.ref = "googleTruthVersion" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockkVersion" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbineVersion" }

androidx-arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidArchTestingVersion" }
core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtxVersion" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHiltVersion" }

